[package]
name = "kinoko"
version = "0.0.1"
authors = ["william <william.hng@outlook.com>"]
edition = "2018"

[dependencies]
toml = "0"
notify = "4"
futures-preview = "0.3.0-alpha.12"
memmap = "0"
regex = "1"
serde = "1"
serde_json = "1"
